// Code generated by MockGen. DO NOT EDIT.
// Source: /home/mezin/go/src/tesseract/beacon-chain/powchain/engine_client.go

// Package blockchain is a generated GoMock package.
package testing

import (
	context "context"
	big "math/big"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	types "github.com/prysmaticlabs/eth2-types"
	enginev1 "gitlab.waterfall.network/waterfall/protocol/coordinator/proto/engine/v1"
	common "gitlab.waterfall.network/waterfall/protocol/gwat/common"
	types0 "gitlab.waterfall.network/waterfall/protocol/gwat/core/types"
)

// MockEngineCaller is a mock of EngineCaller interface.
type MockEngineCaller struct {
	ctrl     *gomock.Controller
	recorder *MockEngineCallerMockRecorder
}

// MockEngineCallerMockRecorder is the mock recorder for MockEngineCaller.
type MockEngineCallerMockRecorder struct {
	mock *MockEngineCaller
}

// NewMockEngineCaller creates a new mock instance.
func NewMockEngineCaller(ctrl *gomock.Controller) *MockEngineCaller {
	mock := &MockEngineCaller{ctrl: ctrl}
	mock.recorder = &MockEngineCallerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEngineCaller) EXPECT() *MockEngineCallerMockRecorder {
	return m.recorder
}

// ExchangeTransitionConfiguration mocks base method.
func (m *MockEngineCaller) ExchangeTransitionConfiguration(ctx context.Context, cfg *enginev1.TransitionConfiguration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeTransitionConfiguration", ctx, cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExchangeTransitionConfiguration indicates an expected call of ExchangeTransitionConfiguration.
func (mr *MockEngineCallerMockRecorder) ExchangeTransitionConfiguration(ctx, cfg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeTransitionConfiguration", reflect.TypeOf((*MockEngineCaller)(nil).ExchangeTransitionConfiguration), ctx, cfg)
}

// ExecutionBlockByHash mocks base method.
func (m *MockEngineCaller) ExecutionBlockByHash(ctx context.Context, hash common.Hash) (*enginev1.ExecutionBlock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecutionBlockByHash", ctx, hash)
	ret0, _ := ret[0].(*enginev1.ExecutionBlock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecutionBlockByHash indicates an expected call of ExecutionBlockByHash.
func (mr *MockEngineCallerMockRecorder) ExecutionBlockByHash(ctx, hash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecutionBlockByHash", reflect.TypeOf((*MockEngineCaller)(nil).ExecutionBlockByHash), ctx, hash)
}

// ExecutionDagCoordinatedState mocks base method.
func (m *MockEngineCaller) ExecutionDagCoordinatedState(ctx context.Context) (*types0.FinalizationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecutionDagCoordinatedState", ctx)
	ret0, _ := ret[0].(*types0.FinalizationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecutionDagCoordinatedState indicates an expected call of ExecutionDagCoordinatedState.
func (mr *MockEngineCallerMockRecorder) ExecutionDagCoordinatedState(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecutionDagCoordinatedState", reflect.TypeOf((*MockEngineCaller)(nil).ExecutionDagCoordinatedState), ctx)
}

// ExecutionDagFinalize mocks base method.
func (m *MockEngineCaller) ExecutionDagFinalize(ctx context.Context, finParams *types0.FinalizationParams) (*types0.FinalizationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecutionDagFinalize", ctx, finParams)
	ret0, _ := ret[0].(*types0.FinalizationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecutionDagFinalize indicates an expected call of ExecutionDagFinalize.
func (mr *MockEngineCallerMockRecorder) ExecutionDagFinalize(ctx, finParams interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecutionDagFinalize", reflect.TypeOf((*MockEngineCaller)(nil).ExecutionDagFinalize), ctx, finParams)
}

// ExecutionDagGetCandidates mocks base method.
func (m *MockEngineCaller) ExecutionDagGetCandidates(ctx context.Context, slot types.Slot) (common.HashArray, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecutionDagGetCandidates", ctx, slot)
	ret0, _ := ret[0].(common.HashArray)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecutionDagGetCandidates indicates an expected call of ExecutionDagGetCandidates.
func (mr *MockEngineCallerMockRecorder) ExecutionDagGetCandidates(ctx, slot interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecutionDagGetCandidates", reflect.TypeOf((*MockEngineCaller)(nil).ExecutionDagGetCandidates), ctx, slot)
}

// ExecutionDagGetOptimisticSpines mocks base method.
func (m *MockEngineCaller) ExecutionDagGetOptimisticSpines(ctx context.Context, fromSpine common.Hash) ([]common.HashArray, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecutionDagGetOptimisticSpines", ctx, fromSpine)
	ret0, _ := ret[0].([]common.HashArray)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecutionDagGetOptimisticSpines indicates an expected call of ExecutionDagGetOptimisticSpines.
func (mr *MockEngineCallerMockRecorder) ExecutionDagGetOptimisticSpines(ctx, fromSpine interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecutionDagGetOptimisticSpines", reflect.TypeOf((*MockEngineCaller)(nil).ExecutionDagGetOptimisticSpines), ctx, fromSpine)
}

// ExecutionDagSyncSlotInfo mocks base method.
func (m *MockEngineCaller) ExecutionDagSyncSlotInfo(ctx context.Context, params *types0.SlotInfo) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecutionDagSyncSlotInfo", ctx, params)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecutionDagSyncSlotInfo indicates an expected call of ExecutionDagSyncSlotInfo.
func (mr *MockEngineCallerMockRecorder) ExecutionDagSyncSlotInfo(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecutionDagSyncSlotInfo", reflect.TypeOf((*MockEngineCaller)(nil).ExecutionDagSyncSlotInfo), ctx, params)
}

// ExecutionDagSyncSpines mocks base method.
func (m *MockEngineCaller) ExecutionDagSyncSpines(ctx context.Context, params common.HashArray) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecutionDagSyncSpines", ctx, params)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecutionDagSyncSpines indicates an expected call of ExecutionDagSyncSpines.
func (mr *MockEngineCallerMockRecorder) ExecutionDagSyncSpines(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecutionDagSyncSpines", reflect.TypeOf((*MockEngineCaller)(nil).ExecutionDagSyncSpines), ctx, params)
}

// ForkchoiceUpdated mocks base method.
func (m *MockEngineCaller) ForkchoiceUpdated(ctx context.Context, state *enginev1.ForkchoiceState, attrs *enginev1.PayloadAttributes) (*enginev1.PayloadIDBytes, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForkchoiceUpdated", ctx, state, attrs)
	ret0, _ := ret[0].(*enginev1.PayloadIDBytes)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ForkchoiceUpdated indicates an expected call of ForkchoiceUpdated.
func (mr *MockEngineCallerMockRecorder) ForkchoiceUpdated(ctx, state, attrs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForkchoiceUpdated", reflect.TypeOf((*MockEngineCaller)(nil).ForkchoiceUpdated), ctx, state, attrs)
}

// GetHeaderByHash mocks base method.
func (m *MockEngineCaller) GetHeaderByHash(ctx context.Context, hash common.Hash) (*types0.Header, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHeaderByHash", ctx, hash)
	ret0, _ := ret[0].(*types0.Header)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHeaderByHash indicates an expected call of GetHeaderByHash.
func (mr *MockEngineCallerMockRecorder) GetHeaderByHash(ctx, hash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHeaderByHash", reflect.TypeOf((*MockEngineCaller)(nil).GetHeaderByHash), ctx, hash)
}

// GetHeaderByNumber mocks base method.
func (m *MockEngineCaller) GetHeaderByNumber(ctx context.Context, nr *big.Int) (*types0.Header, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHeaderByNumber", ctx, nr)
	ret0, _ := ret[0].(*types0.Header)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHeaderByNumber indicates an expected call of GetHeaderByNumber.
func (mr *MockEngineCallerMockRecorder) GetHeaderByNumber(ctx, nr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHeaderByNumber", reflect.TypeOf((*MockEngineCaller)(nil).GetHeaderByNumber), ctx, nr)
}

// GetPayload mocks base method.
func (m *MockEngineCaller) GetPayload(ctx context.Context, payloadId [8]byte) (*enginev1.ExecutionPayload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPayload", ctx, payloadId)
	ret0, _ := ret[0].(*enginev1.ExecutionPayload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPayload indicates an expected call of GetPayload.
func (mr *MockEngineCallerMockRecorder) GetPayload(ctx, payloadId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPayload", reflect.TypeOf((*MockEngineCaller)(nil).GetPayload), ctx, payloadId)
}

// GetTerminalBlockHash mocks base method.
func (m *MockEngineCaller) GetTerminalBlockHash(ctx context.Context) ([]byte, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTerminalBlockHash", ctx)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTerminalBlockHash indicates an expected call of GetTerminalBlockHash.
func (mr *MockEngineCallerMockRecorder) GetTerminalBlockHash(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTerminalBlockHash", reflect.TypeOf((*MockEngineCaller)(nil).GetTerminalBlockHash), ctx)
}

// IsTxLogValid mocks base method.
func (m *MockEngineCaller) IsTxLogValid() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTxLogValid")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsTxLogValid indicates an expected call of IsTxLogValid.
func (mr *MockEngineCallerMockRecorder) IsTxLogValid() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTxLogValid", reflect.TypeOf((*MockEngineCaller)(nil).IsTxLogValid))
}

// NewPayload mocks base method.
func (m *MockEngineCaller) NewPayload(ctx context.Context, payload *enginev1.ExecutionPayload) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewPayload", ctx, payload)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewPayload indicates an expected call of NewPayload.
func (mr *MockEngineCallerMockRecorder) NewPayload(ctx, payload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewPayload", reflect.TypeOf((*MockEngineCaller)(nil).NewPayload), ctx, payload)
}

// MockhttpTimeoutError is a mock of httpTimeoutError interface.
type MockhttpTimeoutError struct {
	ctrl     *gomock.Controller
	recorder *MockhttpTimeoutErrorMockRecorder
}

// MockhttpTimeoutErrorMockRecorder is the mock recorder for MockhttpTimeoutError.
type MockhttpTimeoutErrorMockRecorder struct {
	mock *MockhttpTimeoutError
}

// NewMockhttpTimeoutError creates a new mock instance.
func NewMockhttpTimeoutError(ctrl *gomock.Controller) *MockhttpTimeoutError {
	mock := &MockhttpTimeoutError{ctrl: ctrl}
	mock.recorder = &MockhttpTimeoutErrorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockhttpTimeoutError) EXPECT() *MockhttpTimeoutErrorMockRecorder {
	return m.recorder
}

// Error mocks base method.
func (m *MockhttpTimeoutError) Error() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Error")
	ret0, _ := ret[0].(string)
	return ret0
}

// Error indicates an expected call of Error.
func (mr *MockhttpTimeoutErrorMockRecorder) Error() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockhttpTimeoutError)(nil).Error))
}

// Timeout mocks base method.
func (m *MockhttpTimeoutError) Timeout() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Timeout")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Timeout indicates an expected call of Timeout.
func (mr *MockhttpTimeoutErrorMockRecorder) Timeout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Timeout", reflect.TypeOf((*MockhttpTimeoutError)(nil).Timeout))
}
